# Required by official Signal iOS library (LibSignalClient)
platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  pod 'LibSignalClient', :git => 'https://github.com/signalapp/libsignal.git', :tag => 'v0.87.2'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_ENABLE_EXPLICIT_MODULES'] = 'NO'
    end
    if target.name == 'LibSignalClient'
      target.shell_script_build_phases.each do |phase|
        next unless phase.name.include?('Download libsignal-ffi')

        script = phase.shell_script || ''
        unless script.include?('LIBSIGNAL_FFI_PREBUILD_CHECKSUM:=')
          phase.shell_script = <<~SCRIPT
            : "${LIBSIGNAL_FFI_PREBUILD_CHECKSUM:=dee04b2b1bc49cfe3af9f175cd6d2ccb688dedabeadc3b9a5d225ff1a56d7ba2}"
            : "${LIBSIGNAL_FFI_PREBUILD_ARCHIVE:=libsignal-client-ios-build-v0.87.2.tar.gz}"
            #{script}
          SCRIPT
        end
      end
    end
  end
end
